'use strict';

/**
 * build-i18n.js — generate the static Arabic pages from their English sources +
 * their EN/AR dictionaries.
 *
 * WHY: the site's Arabic is normally applied by JavaScript at runtime
 * (applyLang('ar')), so the HTML that search engines download is English. This
 * bakes the Arabic values into real static HTML at real URLs so Google can index
 * genuine Arabic content.
 *
 * Two pages are generated, each from its own source + dictionary:
 *   - index.html               + assets/js/i18n-data.js      → index-ar.html
 *   - working-with-me/index.html + working-with-me/i18n.js    → working-with-me/index-ar.html
 *
 * For each, it mirrors applyLang('ar') exactly (same data-i18n / -html / -ph
 * attributes), then fixes the <head> for the Arabic URL (title, description,
 * canonical, Open Graph, locale). The generated *-ar.html files are BUILD
 * ARTIFACTS — never edit them by hand; they are git-ignored and regenerated by
 * `npm run build`.
 *
 * Usage: npm run build   (or: node scripts/build-i18n.js)
 */

const fs = require('fs');
const path = require('path');
const { parse } = require('node-html-parser');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://noiceanas.com';

// textContent semantics: escape HTML-special chars (data-i18n-html values are
// intentional markup and are injected raw, like innerHTML).
const escapeText = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/**
 * Generate one static Arabic page.
 * @param {object} o
 * @param {string} o.src   source HTML file, relative to repo root
 * @param {string} o.out   output HTML file, relative to repo root
 * @param {object} o.dict  the `ar` dictionary object (key → string)
 * @param {string} o.arUrl absolute canonical URL of the generated Arabic page
 * @param {Set<string>} o.missing  accumulates keys present in HTML but absent from dict
 * @returns {number} count of localised nodes
 */
function generateArabicPage({ src, out, dict, arUrl, missing }) {
  const html = fs.readFileSync(path.join(ROOT, src), 'utf8');
  const root = parse(html, {
    comment: true,
    blockTextElements: { script: true, style: true, noscript: true, pre: true },
  });

  // 1. <html lang="ar" dir="rtl"> + a lang lock so the runtime script keeps this
  // dedicated page Arabic on load regardless of the visitor's saved preference.
  const htmlEl = root.querySelector('html');
  htmlEl.setAttribute('lang', 'ar');
  htmlEl.setAttribute('dir', 'rtl');
  htmlEl.setAttribute('data-lang-lock', 'ar');

  // 2. Apply the Arabic dictionary — identical rules to applyLang('ar').
  let applied = 0;
  root.querySelectorAll('[data-i18n]').forEach((el) => {
    const k = el.getAttribute('data-i18n');
    const v = dict[k];
    if (v != null) { el.set_content(escapeText(v)); applied++; } else missing.add(k);
  });
  root.querySelectorAll('[data-i18n-html]').forEach((el) => {
    const k = el.getAttribute('data-i18n-html');
    const v = dict[k];
    if (v != null) { el.set_content(v); applied++; } else missing.add(k);
  });
  root.querySelectorAll('[data-i18n-ph]').forEach((el) => {
    const k = el.getAttribute('data-i18n-ph');
    const v = dict[k];
    if (v != null) { el.setAttribute('placeholder', v); applied++; } else missing.add(k);
  });

  // 3. Arabic-ise the <head>. Match by attribute (robust against selector escaping).
  const metas = root.querySelectorAll('meta');
  const links = root.querySelectorAll('link');
  const metaBy = (attr, val) => metas.find((m) => m.getAttribute(attr) === val);
  const linkBy = (rel) => links.find((l) => l.getAttribute('rel') === rel);
  const setMeta = (attr, val, content) => { const el = metaBy(attr, val); if (el && content != null) el.setAttribute('content', content); };

  const titleEl = root.querySelector('title');
  if (titleEl) titleEl.set_content(escapeText(dict['meta.title']));
  setMeta('name', 'description', dict['meta.description']);
  const canonical = linkBy('canonical');
  if (canonical) canonical.setAttribute('href', arUrl);
  setMeta('property', 'og:url', arUrl);
  setMeta('property', 'og:title', dict['meta.title']);
  setMeta('property', 'og:description', dict['meta.description']);
  setMeta('property', 'og:locale', 'ar_SA');
  setMeta('property', 'og:image:alt', dict['meta.title']);
  setMeta('name', 'twitter:title', dict['meta.title']);
  setMeta('name', 'twitter:description', dict['meta.description']);
  setMeta('name', 'twitter:image:alt', dict['meta.title']);

  // 4. Serialise with a clean doctype + a "generated" banner.
  const body = root.toString().replace(/^\s*<!doctype html>\s*/i, '');
  const banner =
    '<!DOCTYPE html>\n' +
    '<!-- GENERATED by scripts/build-i18n.js — do NOT edit by hand.\n' +
    `     Source: ${src} + its i18n dictionary. Rebuild: npm run build -->\n`;
  fs.writeFileSync(path.join(ROOT, out), banner + body + '\n');
  return applied;
}

// --- pages to generate ---------------------------------------------------
const PAGES = [
  {
    src: 'index.html',
    out: 'index-ar.html',
    dict: require('../assets/js/i18n-data.js').ar,
    arUrl: `${SITE}/index-ar`,
  },
  {
    src: 'working-with-me/index.html',
    out: 'working-with-me/index-ar.html',
    dict: require('../working-with-me/i18n.js').ar,
    arUrl: `${SITE}/working-with-me/index-ar`,
  },
];

const missing = new Set();
PAGES.forEach((p) => {
  const applied = generateArabicPage({ ...p, missing });
  console.log(`${p.out} generated — ${applied} i18n nodes localised.`);
});

// Fail loudly (non-zero exit → CI fails) if any source has keys the dictionary
// is missing, so an Arabic page is never silently half-translated.
if (missing.size) {
  console.error(`\n⚠  ${missing.size} data-i18n key(s) missing from a dictionary:`);
  console.error('   ' + [...missing].join(', '));
  process.exitCode = 1;
}
