'use strict';

/**
 * build-i18n.js — generate the static Arabic page (index-ar.html) from the
 * English source (index.html) + the shared dictionary (assets/js/i18n-data.js).
 *
 * WHY: the site's Arabic is normally applied by JavaScript at runtime
 * (applyLang('ar') in script.js), so the HTML that search engines download is
 * English. This bakes the Arabic values into a real static HTML file at a real
 * URL (/index-ar) so Google can index genuine Arabic content — reclaiming the
 * Arabic search result the old MyWebsite used to rank for.
 *
 * It mirrors applyLang('ar') exactly (same data-i18n / -html / -ph attributes),
 * then fixes the <head> for the Arabic URL (title, description, canonical,
 * Open Graph, locale). index-ar.html is a BUILD ARTIFACT — never edit it by
 * hand; it is git-ignored and regenerated by `npm run build`.
 *
 * Usage: npm run build   (or: node scripts/build-i18n.js)
 */

const fs = require('fs');
const path = require('path');
const { parse } = require('node-html-parser');
const I18N = require('../assets/js/i18n-data.js');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://noiceanas.com';
const AR_URL = `${SITE}/index-ar`;
const ar = I18N.ar;

// textContent semantics: escape HTML-special chars (data-i18n-html values are
// intentional markup and are injected raw, like innerHTML).
const escapeText = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const src = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const root = parse(src, {
  comment: true,
  blockTextElements: { script: true, style: true, noscript: true, pre: true },
});

// 1. <html lang="ar" dir="rtl"> + a lang lock so script.js keeps this dedicated
// page Arabic on load regardless of the visitor's saved preference (see the
// data-lang-lock handling in script.js).
const htmlEl = root.querySelector('html');
htmlEl.setAttribute('lang', 'ar');
htmlEl.setAttribute('dir', 'rtl');
htmlEl.setAttribute('data-lang-lock', 'ar');

// 2. Apply the Arabic dictionary — identical rules to applyLang('ar').
const missing = new Set();
let applied = 0;
root.querySelectorAll('[data-i18n]').forEach((el) => {
  const k = el.getAttribute('data-i18n');
  const v = ar[k];
  if (v != null) { el.set_content(escapeText(v)); applied++; } else missing.add(k);
});
root.querySelectorAll('[data-i18n-html]').forEach((el) => {
  const k = el.getAttribute('data-i18n-html');
  const v = ar[k];
  if (v != null) { el.set_content(v); applied++; } else missing.add(k);
});
root.querySelectorAll('[data-i18n-ph]').forEach((el) => {
  const k = el.getAttribute('data-i18n-ph');
  const v = ar[k];
  if (v != null) { el.setAttribute('placeholder', v); applied++; } else missing.add(k);
});

// 3. Arabic-ise the <head>. Match by attribute (robust against selector escaping).
const metas = root.querySelectorAll('meta');
const links = root.querySelectorAll('link');
const metaBy = (attr, val) => metas.find((m) => m.getAttribute(attr) === val);
const linkBy = (rel) => links.find((l) => l.getAttribute('rel') === rel);
const setMeta = (attr, val, content) => { const el = metaBy(attr, val); if (el && content != null) el.setAttribute('content', content); };

const titleEl = root.querySelector('title');
if (titleEl) titleEl.set_content(escapeText(ar['meta.title']));
setMeta('name', 'description', ar['meta.description']);
const canonical = linkBy('canonical');
if (canonical) canonical.setAttribute('href', AR_URL);
setMeta('property', 'og:url', AR_URL);
setMeta('property', 'og:title', ar['meta.title']);
setMeta('property', 'og:description', ar['meta.description']);
setMeta('property', 'og:locale', 'ar_SA');
setMeta('property', 'og:image:alt', ar['meta.title']);
setMeta('name', 'twitter:title', ar['meta.title']);
setMeta('name', 'twitter:description', ar['meta.description']);
setMeta('name', 'twitter:image:alt', ar['meta.title']);

// 4. Serialise with a clean doctype + a "generated" banner.
let out = root.toString().replace(/^\s*<!doctype html>\s*/i, '');
const banner =
  '<!DOCTYPE html>\n' +
  '<!-- GENERATED by scripts/build-i18n.js — do NOT edit by hand.\n' +
  '     Source: index.html + assets/js/i18n-data.js. Rebuild: npm run build -->\n';
fs.writeFileSync(path.join(ROOT, 'index-ar.html'), banner + out + '\n');

// 5. Report (and fail loudly if the source has keys the dictionary is missing).
console.log(`index-ar.html generated — ${applied} i18n nodes localised.`);
if (missing.size) {
  console.error(`\n⚠  ${missing.size} data-i18n key(s) missing from I18N.ar:`);
  console.error('   ' + [...missing].join(', '));
  process.exitCode = 1;
}
